apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linktree-web-ing
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "godtolo.cubit.com.uy"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: linktree-web-svc
            port:
              number: 80
