apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pgsql-prod-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem

